[package]
org = "ballerinax"
name = "health.fhirr4"
version = "1.0.8"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "service"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.0.1"
repository="local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "4.0.1"
repository="local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "1.0.1"
repository="local"

[[platform.java11.dependency]]
groupId = "io.ballerinax"
artifactId = "fhirr4-native"
version = "${project.version}"
path = "./fhirr4-native-${project.version}.jar"
